// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using csharpCamadas.API.DAL;

#nullable disable

namespace csharpCamadas.API.Migrations
{
    [DbContext(typeof(csharpCamadasContext))]
    partial class csharpCamadasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("csharpCamadas.API.Models.Motoristum", b =>
                {
                    b.Property<int>("MotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mot_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotId"), 1L, 1);

                    b.Property<int?>("MotIdade")
                        .HasColumnType("int")
                        .HasColumnName("mot_idade");

                    b.Property<string>("MotNome")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mot_nome");

                    b.Property<int?>("VeiId")
                        .HasColumnType("int")
                        .HasColumnName("vei_id");

                    b.HasKey("MotId")
                        .HasName("PK__Motorist__E0752241BCD10E26");

                    b.HasIndex("VeiId");

                    b.ToTable("Motorista");
                });

            modelBuilder.Entity("csharpCamadas.API.Models.Posto", b =>
                {
                    b.Property<int>("PosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pos_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PosId"), 1L, 1);

                    b.Property<string>("PosCidade")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pos_cidade");

                    b.Property<string>("PosEndereco")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pos_endereco");

                    b.Property<string>("PosNome")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pos_nome");

                    b.HasKey("PosId")
                        .HasName("PK__Posto__D1A4EB1218119F5C");

                    b.ToTable("Posto");
                });

            modelBuilder.Entity("csharpCamadas.API.Models.TiposDeCombustivel", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Tipo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoId"), 1L, 1);

                    b.Property<int?>("PosId")
                        .HasColumnType("int")
                        .HasColumnName("pos_id");

                    b.Property<string>("TipoNome")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Tipo_nome");

                    b.Property<double?>("TipoValor")
                        .HasColumnType("float")
                        .HasColumnName("Tipo_valor");

                    b.HasKey("TipoId")
                        .HasName("PK__TiposDeC__94F920011E35D731");

                    b.HasIndex("PosId");

                    b.ToTable("TiposDeCombustivel");
                });

            modelBuilder.Entity("csharpCamadas.API.Models.Veiculo", b =>
                {
                    b.Property<int>("VeiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vei_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeiId"), 1L, 1);

                    b.Property<string>("VeiNome")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vei_nome");

                    b.Property<string>("VeiPlaca")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("vei_placa");

                    b.HasKey("VeiId")
                        .HasName("PK__Veiculo__136D0F563BBE0B6D");

                    b.ToTable("Veiculo");
                });

            modelBuilder.Entity("csharpCamadas.API.Models.Motoristum", b =>
                {
                    b.HasOne("csharpCamadas.API.Models.Veiculo", "Vei")
                        .WithMany("Motorista")
                        .HasForeignKey("VeiId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Motorista__vei_i__286302EC");

                    b.Navigation("Vei");
                });

            modelBuilder.Entity("csharpCamadas.API.Models.TiposDeCombustivel", b =>
                {
                    b.HasOne("csharpCamadas.API.Models.Posto", "Pos")
                        .WithMany("TiposDeCombustivels")
                        .HasForeignKey("PosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__TiposDeCo__pos_i__2B3F6F97");

                    b.Navigation("Pos");
                });

            modelBuilder.Entity("csharpCamadas.API.Models.Posto", b =>
                {
                    b.Navigation("TiposDeCombustivels");
                });

            modelBuilder.Entity("csharpCamadas.API.Models.Veiculo", b =>
                {
                    b.Navigation("Motorista");
                });
#pragma warning restore 612, 618
        }
    }
}
